### ISSUE TITLE
License

### ISSUE THREAD

**Issue by RasheedAZ** [flathub/net.warsow.Warsow#2]
Hi. Thanks for packaging this. It's listed as proprietary but I was under the impression it's open source?

Source code is provided on website:

https://www.warsow.net/download

and the readme says "Fully open-source under the GPLv2 and easy to mod"

https://github.com/Warsow

**Comment by Mailaender** [comment]
It had proprietary bits in the past https://lists.fedoraproject.org/pipermail/legal/2014-May/002454.html, but we don't list them as proprietary:
https://github.com/flathub/net.warsow.Warsow/blob/116d86c312b1ab2189beac146950dcbe7543e62f/warsow.appdata.xml#L12

which should match the README exactly:

```
Warsow assets are licensed under the Creative Commons Attribution-ShareAlike 4.0 International License.
To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/4.0/ or send a letter to Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.

Exceptions:
The assets found within the following archives:
- basewsw/data0_000_nonfree_21.pk3
- basewsw/data0_000_nonfree_21pure.pk3
- basewsw/tex_000_nonfree.pk3
are licensed under the Creative Commons Attribution-NoDerivatives 4.0 International License.
To view a copy of this license, visit http://creativecommons.org/licenses/by-nd/4.0/ or send a letter to Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
```
